import Head from "next/head"


export default function layout(props){
    return(
        <div className='bg-gray-300' >
            <Head>
                <title>{props.tittle || 'Create Next Pokedex'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='container mx-auto max-w-xl pt-8 min-h-screen' >
                {props.children}
            </main>
        </div>
    )
}