import Head from "next/head"
import getTWClasses from "../utility"


export default function layout(props){

    const [parentClasses, childrensClasses] = getTWClasses('layoutComponent')

    return(
        <div className={parentClasses} >
            <Head>
                <title>{props.tittle || 'Create Next Pokedex'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={childrensClasses.main.join(' ')} >
                {props.children}
            </main>
        </div>
    )
}